### ISSUE TITLE
Using a class rather than an inline function for the component property in Route

### ISSUE THREAD

**Issue by tezzutezzu** [taming-the-state-in-react/react-firebase-authentication#8]
Hi @rwieruch and thanks for your hard work on this.

In your example, shouldn't the Route components' value be a class rather than an inline function?

According to [react-router docs](https://reacttraining.com/react-router/web/api/Route/component ),  in that way a new component is created every time rather than being updated.

Here's a proposed change:

```
<Route exact path={routes.LANDING} component={LandingPage} />

<Route exact path={routes.SIGN_UP} component={SignUpPage} />

<Route exact path={routes.SIGN_IN} component={SignInPage} />

<Route exact path={routes.PASSWORD_FORGET} component={PasswordForgetPage} />

<Route exact path={routes.HOME} component={HomePage} />

<Route exact path={routes.ACCOUNT} component={AccountPage} />
```

**Comment by rwieruch** [comment]
Good point. Do you have the time to fix it over here https://github.com/rwieruch/the-road-to-react-with-firebase? I will adjust the coding projects afterward.

**Comment by rwieruch** [comment]
Fixed in tutorial, will fix later in applications.
