### ISSUE TITLE
Pushing to firebase storage and database 

### ISSUE THREAD

**Issue by junniepat** [taming-the-state-in-react/react-firebase-authentication#9]
How do i push to firebase storage and database, i created it following the style you used but still it throws an error.

**Comment by junniepat** [comment]
I already fixed it but I went through another route.

**Comment by rwieruch** [comment]
Ah okay. Sorry, I must have missed the E-Mail! I hope you are good now!

**Comment by junniepat** [comment]
It's about react js firebase roles

Patrick .U. Igwe
Front End Web Developer.
Design Meister.
